---
- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: install zsh
  action: "{{backcompat_pkg_mgr}} name=zsh"
  sudo: yes
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install zsh
  command: dnf install -y zsh
  args:
    creates: /bin/zsh
  sudo: yes
  when: backcompat_pkg_mgr == "dnf"
